### ISSUE TITLE
Compile single-component instead of chunks on server-side-only?

### ISSUE THREAD

**Issue by espen42** [enonic/lib-react4xp#152]
Ref https://github.com/enonic/lib-react4xp/issues/106: 

On the server side, when a react4xp app is refreshed, compiled entry and chunk assets are read/cached into the SSR engine on first usage. This takes a lot of time. Solving #106 will involve more efficient lazy loading. But even on an optimal completion of that, it will still be a lot of wasted time re-caching whole chunks when only small parts of them are updated during development. 

So while collecting things in content-hashed chunks is a good way to optimize assets for frontend requests, it's the other way around for the cache-functions approach in the SSR engine.

One solution _could_ be to implement a parallel build system to compile the JSX source files into different SSR-only assets, not chunked but kept as small as possible, so that source code changes would require re-reading and re-caching as little as possible in the SSR engine. However, this increases build-time complexity hugely. Also the runtime handling would need adjustment. Besides, it risks breaking isomorphy: is it possible to guarantee that it's the same code running backend and frontend when the assets are structured differently?

**Comment by ComLock** [comment]
Code splitting (Chunking) is what causes shared code to be split into "smaller" files, rather than being bundled multiple times.

It might be faster to load one "big" file, rather than say 2 half-sized files.

However as soon as you have more than one component on a page that shares any code, the loading 2 "big" files is slower than loading 3 small files...

For simplicity let's say component A is 10kB, and component B is 20kb, and the shared code is 30kB.
It's faster to load 10+20+30=60 kB rather than (10+30)+(20+30)=90 kB...

Even if the shared code is smaller, lets say component A is 30kB, and component B is 20kb, and the shared code is 10kB.
It's faster to load 30+20+10=60 kB rather than (30+10)+(20+10)=70 kB...

The total loaded size will always be larger when shared code is (duplicated) bundled more than once.
